# copied from https://game.ci/docs/github/getting-started

name: Actions 😎

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.MOZI_LIC }}
      UNITY_EMAIL: ${{ secrets.MOZI_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.MOZI_PWD }}
    # for the test step: "Resource not accessible by integration"
    permissions:
      checks: write
    
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        id: myTestStep
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: ${{ steps.myTestStep.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.myTestStep.outputs.coveragePath }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
